### ISSUE TITLE
error run apps

### ISSUE THREAD

**Issue by raingart** [cryzed/Feedbuffer#1]
~/D/Feedbuffer-master > ls -lt                                                                                                                        
drwxr-xr-x 2 art users 4.0K Jul  2  2016 feedbuffer/
-rw-r--r-- 1 art users 1.7K Jul  2  2016 .gitignore
-rw-r--r-- 1 art users 1.1K Jul  2  2016 LICENSE
-rwxr-xr-x 1 art users  659 Jul  2  2016 main.py*
-rw-r--r-- 1 art users 1.4K Jul  2  2016 README.md
-rw-r--r-- 1 art users  198 Jul  2  2016 TODO.md

✘ ~/D/Feedbuffer-master > ./main.py                                                                                                                   
Failed to execute process './main.py'. Reason:
exec: Exec format error
The file './main.py' is marked as an executable but could not be run by the operating system.

X appears running (sight on the similarity xkill). click, click, click .. and this:

ツ~/D/Feedbuffer-master > sudo ./main.py                                                                                                                
import: unable to load module `/usr/lib/ImageMagick-6.9.7//modules-Q16HDRI/coders/ps.la': file not found @ error/module.c/OpenModule/1302.
import: no encode delegate for this image format `PS' @ error/constitute.c/WriteImage/1184.
import: unable to load module `/usr/lib/ImageMagick-6.9.7//modules-Q16HDRI/coders/ps.la': file not found @ error/module.c/OpenModule/1302.
import: no encode delegate for this image format `PS' @ error/constitute.c/WriteImage/1184.
import: unable to load module `/usr/lib/ImageMagick-6.9.7//modules-Q16HDRI/coders/ps.la': file not found @ error/module.c/OpenModule/1302.
import: no encode delegate for this image format `PS' @ error/constitute.c/WriteImage/1184.
import: unable to load module `/usr/lib/ImageMagick-6.9.7//modules-Q16HDRI/coders/ps.la': file not found @ error/module.c/OpenModule/1302.
import: no encode delegate for this image format `PS' @ error/constitute.c/WriteImage/1184.
./main.py: line 7: from: command not found
./main.py: line 8: from: command not found
./main.py: line 9: from: command not found
./main.py: line 11: syntax error near unexpected token `('
./main.py: line 11: `_logger = log.get_logger(__name__)'

what am I doing wrong?

ツ~/D/Feedbuffer-master > uname -a                                                                                                                     
Linux hostname 4.9.9-1-ARCH #1 SMP PREEMPT Thu Feb 9 19:07:09 CET 2017 x86_64 GNU/Linux

ツ~/D/Feedbuffer-master > pip list --format=legacy                                                                                                    
appdirs (1.4.0)
autopep8 (1.2.4)
beautifulsoup4 (4.5.3)
CacheControl (0.12.0)
cheroot (5.1.0)
CherryPy (10.1.1)
configparser (3.5.0)
feedparser (5.2.1)
furl (0.5.6)
louis (3.0.0)
lxml (3.7.3)
msgpack-python (0.4.8)
orderedmultidict (0.7.11)
packaging (16.8)
peewee (2.8.5)
pep8 (1.7.0)
pip (9.0.1)
portend (1.8)
pyparsing (2.1.10)
python-libtorrent (1.1.1)
pytz (2016.10)
requests (2.13.0)
setuptools (34.2.0)
six (1.10.0)
tempora (1.6.1)

**Comment by cryzed** [comment]
`main.py` doesn't have a shebang, use `python main.py` instead to execute the script.

**Comment by raingart** [comment]
it worked, thanks
